name: Bug report
description: Report a reproducible bug in Open GR--WM
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce.
      placeholder: |
        1. Go to...
        2. Click...
        3. Ask query...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include local setup details.
      placeholder: |
        - OS:
        - Python version:
        - Streamlit version:
        - Ollama version:
        - Models installed:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or screenshots.
      placeholder: Add logs, stack traces, and screenshots here.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues.
          required: true
        - label: I can reproduce this on the latest main branch.
          required: true
